site_name: frameworkdocs
nav:
    - index: index.md
    - 框架说明文档: frameHelp.md
    - YAML编写规范: yamlHelp.md
    - MarkDown编写规范: mdHelp.md
    - 浏览器驱动下载: browser.md
    - PIP资源下载慢: pip.md
    - 测试数据配置规范: testdata.md
    - 测试用例编写规范: testcase.md
    - 页面元素编写规范: element.md
    - selenium指导: selenium.md
theme: readthedocs
repo_url: https://github.com/chrishshare/framework
site_description: framework
